service: serverless-ci

# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  environment:
    STAGE: ${self:provider.stage}
  logRetentionInDays: 7

package:
  individually: true
  excludeDevDependencies: true

functions:
  helloworld:
    handler: handler.helloworld
